### ISSUE TITLE
...

### ISSUE THREAD

**Issue by tarik02** [KsyMC/ForgePE#10]
Can you push full ForgePE to compile quickly or instructions to compiling.

**Comment by Flaplim** [comment]
You need 'libsubstrate.so', 'libfmod.so' and 'fmod.jar'.

If you are using android studio..
1) Go to the path where you cloned the project.
2) Put 'fmod.jar' in ForgePE/app/libs/ (You might have to create it)
3) Put 'libsubstrate.so' and 'libfmod.so' in ForgePE/app/src/main/jnilibs (You might have to create it too)
4) Open Android Studio
5) Select 'Open an existing Android Studio project'
6) Go to the Path where you cloned ForgePE
7) Select the Project and click OK
8) Press Ctrl + F9
9) Click the green triangle.
10) Test it

**Comment by tarik02** [comment]
@Flaplim, thank you!
