### ISSUE TITLE
The Launcher 

### ISSUE THREAD

**Issue by FranklinTremplin** [KsyMC/ForgePE#2]
How to download the launcher

**Comment by ghost** [comment]
ForgePE is in-development now, and doesn't work yet.

**Comment by ghost** [comment]
:'(

**Comment by ghost** [comment]
@64FF00 How did you be iMCPE plugin developer? Did iJoshuaHD offered to you?

**Comment by ghost** [comment]
@ns827 넹

**Comment by ghost** [comment]
@ns827 원하신다면 들어오실래요

**Comment by ghost** [comment]
@64FF00 가고는 싶어도 고입 입시라는 크리가....ㅠ

//Please use only English here, because other users are also reading this. :P

**Comment by ghost** [comment]
@ns827 고입 입시 별거 아녀

**Comment by ghost** [comment]
@ns827 아녀요*

**Comment by ghost** [comment]
@ns827 들어오실 생각있으면 갠톡 ㄱ

**Comment by ghost** [comment]
@ns827 Is there an expected release date?

**Comment by ghost** [comment]
@Comedyman937 I am not a main developer, and @KsyMC is currently offline I think.

**Comment by ghost** [comment]
@Comedyman937 Just unknown, since hes been suffering from school exams :P

**Comment by ghost** [comment]
@64ff00 he said*
